[package]
name = "rchip16"
version = "0.1.0"
authors = ["FlyingGaz <FlyingGaz@users.noreply.github.com>"]
edition = "2018"

[dependencies]
rand = { version = "0.7.0", features = ["small_rng"] }
minifb = "0.11.2"
cpal = "0.9.0"
